repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.29.0
  hooks:
  - id: yapf
    language: system

- repo: git://github.com/guykisel/prospector-mirror
  rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
  hooks:
  - id: prospector
    language: system
    exclude: '^(doc/)|(examples/)|(futures/)'
